[package]
name = "flltr"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "*", default-features = false }
colored = "2.0.0"
